server:
  port: 9095

logging:
  level:
    org.springframework: DEBUG


messages:
  basename: messages
   
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  security:
    user:
      name: admin
      password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      
      
  output:
    ansi:
      enabled: NEVER